# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

author: Martynas Dervinis

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/dervinism/dervinism.github.io  # Online location of your book
  path_to_book: _build  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_edit_page_button: false
  use_issues_button: false
  use_repository_button: false
  use_multitoc_numbering: false
  home_page_in_navbar: false
        
